[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "ophix-confs"
version = "2026.05.01.01"
description = "Configuration snippets domain plugin for Ophix Project Servers"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [
    { name = "Ophix Project" }
]
dependencies = [
    "ophix-server-base>=2026.05.01.01",
    "ophix-codemirror>=2026.05.01.02",
    "PyYAML>=6.0",
]

[project.entry-points."ophix.plugins"]
ophix_confs = "ophix_confs"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
ophix_confs = [
    "docs/**/*",
    "locale/**/*",
    "migrations/**/*",
    "deploy_templates/**/*",
]
