[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "ophix-confs"
version = "2026.04.10.01"
description = "Configuration snippets domain plugin for Ophix Project Servers"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [
    { name = "Ophix Project" }
]
dependencies = [
    "ophix-server-base>=2026.03.23.01",
    "ophix-codemirror>=2026.04.05.01",
    "PyYAML>=6.0",
]

[project.entry-points."ophix.plugins"]
ophix_confs = "ophix_confs"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
ophix_confs = [
    "docs/**/*",
    "migrations/**/*",
    "deploy_templates/**/*",
]
