# Generated by Django 6.0.4 on 2026-05-01 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophix_confs', '0002_initial_formats'),
        ('ophix_core', '0003_alter_accesslog_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientconfiguration',
            name='can_delete',
            field=models.BooleanField(default=False, help_text='Client may delete this artifact.', verbose_name='can delete'),
        ),
        migrations.AlterField(
            model_name='clientconfiguration',
            name='can_share',
            field=models.BooleanField(default=False, help_text='Reserved: future client-driven sharing. Currently unused.', verbose_name='can share'),
        ),
        migrations.AlterField(
            model_name='clientconfiguration',
            name='can_update',
            field=models.BooleanField(default=False, help_text='Client may overwrite this artifact.', verbose_name='can update'),
        ),
        migrations.AlterField(
            model_name='clientconfiguration',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ophix_core.client', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='clientconfiguration',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Client can read this artifact (can_read).', verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='clientconfiguration',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
    ]
